# Generated by Django 5.0.3 on 2024-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('second_name', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'Resume',
                'get_latest_by': 'Res',
            },
        ),
    ]
